

services:
  nginx:
    image: nginx
    env_file:
      - .env
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./hleb:/hleb
      - ./log:/log
    ports:
      - '${SERVER_EXTERNAL_PORT}:80'

  php:
    environment:
      PHP_IDE_CONFIG: 'serverName=toaster'
    build: ./docker
    env_file:
      - .env
    volumes:
      - ./hleb:/hleb
      - ./log:/log
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./.env:/hleb/.env:ro

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123  # или другой надежный пароль
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '${DATABASE_EXTERNAL_PORT}:3306'
